import time, os
def clear():
  os.system("clear")
print("|  Loading")
time.sleep(0.15)
clear()
print("/  Loading")
time.sleep(0.15)
clear()
print("-  Loading")
time.sleep(0.15)
clear()
print("\\  Loading.")
time.sleep(0.15)
clear()
print("|  Loading.")
time.sleep(0.15)
clear()
print("/  Loading.")
time.sleep(0.15)
clear()
print("-  Loading..")
time.sleep(0.15)
clear()
print("\\  Loading..")
time.sleep(0.15)
clear()
print("|  Loading..")
time.sleep(0.15)
clear()
print("/  Loading...")
time.sleep(0.15)
clear()
print("-  Loading...")
time.sleep(0.15)
clear()
print("\\  Loading...")
time.sleep(0.15)
clear()
print("|  Loading")
time.sleep(0.15)
clear()
print("/  Loading")
time.sleep(0.15)
clear()
print("-  Loading")
time.sleep(0.15)
clear()
print("\\  Loading.")
time.sleep(0.15)
clear()
print("|  Loading.")
time.sleep(0.15)
clear()
print("/  Loading.")
time.sleep(0.15)
clear()
print("-  Loading..")
time.sleep(0.15)
clear()
print("\\  Loading..")
time.sleep(0.15)
clear()
print("|  Loading..")
time.sleep(0.15)
clear()
print("/  Loading...")
time.sleep(0.15)
clear()